---
- hosts: web-servers
  remote_user: root
  tasks:
    - name: test connection
      ping:
      remote_user: Damodaran
      register: output
    - name: output console
      debug:
      msg: "{{output}}"
  
